### PR TITLE
common: add hasOwnProperty to for...in loop. Fixes #1984.

### LINKED ISSUE #1984: BigQuery table.import() complains about not having a project ID.
Despite having specified the project ID when creating the `BigQuery` object, I'm getting this error about there not being one specified when trying to use `table.import()`.

#### Environment details

  - OS: Win 10 Pro
  - Node.js version: v7.5.0
  - npm version: v4.1.2
  - google-cloud-node version: bigquery v0.7.0

#### Steps to reproduce

  1. require `@google-cloud/bigquery`
  2. create `BigQuery` object specifying `projectId` in options
  3. create `dataset` object from `BigQuery` object, then `table` object from `dataset`
  4. `table.import(jsonFile).then(...);`

#### Error
```
Sorry, we cannot connect to Google Cloud Services without a project ID. You may specify one with an environment variable named "GCLOUD_PROJECT". See https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/authentication for a detailed guide on creating an authenticated connection.
    at Object.<anonymous> (%project%\node_modules\@google-cloud\common\src\util.js:55:29)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (%project%\node_modules\@google-cloud\common\src\service-object.js:32:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

### PR DESCRIPTION
**Pull request by AKPWebDesign**
This is to stop the for...in loop from looping over properties that
aren't actually part of the object, which can lead to the call stack
overflowing under certain circumstances.

### CODE REVIEW

**Comment by AKPWebDesign** [comment]
I signed it!

File: packages/common/src/util.js [hunk 1]
```diff
@@ -518,7 +518,9 @@ function replaceProjectIdToken(value, projectId) {
 
   if (is.object(value)) {
     for (var opt in value) {
-      value[opt] = replaceProjectIdToken(value[opt], projectId);
+      if (value.hasOwnProperty(value)) {
```
Comment (stephenplusplus) [inline packages/common/src/util.js]: Shouldn't this be `if (value.hasOwnProperty(opt))` ?

Comment (AKPWebDesign) [inline packages/common/src/util.js]: Yeah, you're probably right. That's what I get for working while tired.

Comment (stephenplusplus) [inline packages/common/src/util.js]: Haha, been there!

**Comment by stephenplusplus** [comment]
Thank you!
