### PR TITLE
Throw TypeError if we get a Number to spanner.date.

### LINKED ISSUE #2097: Inserting Date values into Spanner date column fails
What I want to do:

```js
myTable.insert({id: 1, start_date: new Date(1976, 4, 1)}).then(function (data) {
  console.log(data);
});
```

What I have to do instead :(

```js
myTable.insert({id: 1, start_date: '1976-04-01'},).then(function (data) {
  console.log(data);
});
```

Can we make dates do "the right thing" ? Or is that not possible?

### PR DESCRIPTION
**Pull request by lukesneeringer**
Fixes #2097.

### CODE REVIEW

File: packages/spanner/src/codec.js [hunk 1]
```diff
@@ -26,6 +26,10 @@ var commonGrpc = require('@google-cloud/common-grpc');
 var is = require('is');
 
 function SpannerDate(value) {
+  if (is.number(value)) {
```
Comment (jgeewax) [inline packages/spanner/src/codec.js]: I don't think this is what we want... I think this should choke on more than one argument. For example:

```js
> new Date(1490195461000)
2017-03-22T15:11:01.000Z
```

I'm worried about people passing the arguments to a "date":

```js
> new Date(2000, 99, 41)
2008-05-11T04:00:00.000Z 
```

So this is really about anything more than one argument.

Comment (lukesneeringer) [inline packages/spanner/src/codec.js]: Sold. I thought timestamps did not work properly, but they do.

**Comment by stephenplusplus** [comment]
Thank you, LGTM, I just need to make sure my code style commits didn't break the tests before merging.
