### PR TITLE
treat partial errors as callback(err)ors

### LINKED ISSUE #1644: expose failed operations as callback(err)
*Thread hijacked by @stephenplusplus*

Some upstream API methods exist, which can return a code 200, however, a portion of the request failed-- partial failure. We've been returning these partial failures to users separate from the `err` property of a `callback(err)`. This is confusing, and we should just do it like this:

```
methodThatCanPartiallyFail('...', function (err, apiResponse) {
  if (err) {
    // err.code = 'INSERT_ERROR'
    // err.errors = [insert errors]
  }
})
```

#### Methods that need to be updated

- bigquery/table#insert
- bigtable/table#mutate
- vision#detect

*Back to you, @c0b...*

am playing around streaming data into tables, with this nodejs-docs-samples code,

https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/bigquery/tables.js#L194-L207

a table created with `name:integer,value:string` as schema but inserted name as string, the program runs ok says 1 row inserted but nothing show up in bigquery console, until I print the `apiResponse` I found the error, but it turns out the callback function's first err is a null, where it shouldn't be; if user has to check `apiResponse` anyway, that makes the first err check not meaningful

``` js
  table.insert(rows, function (err, insertErrors, apiResponse) {
    if (err) {          // why this branch not triggered
      return callback(err);
    }
    ...
```

``` console
$ bq mk new_dataset.new_table name:integer,value:string

$ node ./bigquery/tables.js insert new_dataset newtable '[{ "name": "abc" }]'
Inserted 1 row(s)!
{ datasetId: 'new_dataset',
  tableId: 'newtable',
  rows: [ { name: 'abc' } ],
  callback: [Function],
  err: null,
  insertErrors: 
   [ { errors: 
        [ { message: 'Cannot convert value to integer (bad value).',
            reason: 'invalid' } ],
       row: { name: 'abc' } } ],
  apiResponse: 
   { kind: 'bigquery#tableDataInsertAllResponse',
     insertErrors: 
      [ { index: 0,
          errors: 
           [ { reason: 'invalid',
               location: 'name',
               debugInfo: 'generic::invalid_argument: Cannot convert value to integer (bad value).',
               message: 'Cannot convert value to integer (bad value).' } ] } ] } }
```

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #1644

#### To Dos

  - [x] Split apart common/util into a separate PR: #1764
  - **BigQuery**
    - [x] Docs
    - [x] Unit tests
    - [x] System tests
  - **Bigtable**
    - [x] Docs
    - [x] Unit tests
    - [x] System tests
  - **Vision**
    - [x] Docs
    - [x] Unit tests
    - [x] System tests

### CODE REVIEW

**Comment by stephenplusplus** [comment]
@callmehiphop PTAL

File: packages/vision/src/index.js [hunk 1]
```diff
@@ -385,16 +386,30 @@ Vision.prototype.detect = function(images, options, callback) {
...
       var detections = images
         .map(groupDetectionsByImage)
         .map(assignTypeToEmptyAnnotations)
         .map(combineErrors)
         .map(flattenAnnotations)
-        .map(decorateAnnotations);
+        .map(decorateAnnotations)
+        .filter(function(annotation) {
+          // Remove annotations that had errors.
+          return annotation;
```
Comment (callmehiphop) [inline packages/vision/src/index.js]: Should we pushing errors into `partialFailureErrors` somewhere around here?

Comment (callmehiphop) [inline packages/vision/src/index.js]: nvm! spoke too soon

Comment (stephenplusplus) [inline packages/vision/src/index.js]: Yeah, that sounds cleaner!

File: packages/bigquery/src/table.js [hunk 2]
```diff
@@ -1015,18 +1015,19 @@ Table.prototype.import = function(source, metadata, callback) {
...
- *   //
- *   // insertErrors[].row (original individual row object passed to `insert`)
- *   // insertErrors[].errors[].reason
- *   // insertErrors[].errors[].message
- *
- *   // See https://developers.google.com/bigquery/troubleshooting-errors for
- *   // recommendations on handling errors.
+ *   //   An API error or partial failure occurred.
+ *
+ *   if (err.name === 'PartialFailureError') {
```
Comment (stephenplusplus) [inline packages/bigquery/src/table.js]: Maybe a `code`?

```js
if (err.code === 'PARTIAL_FAILURE') {
  // ...
}
```

Comment (callmehiphop) [inline packages/bigquery/src/table.js]: Well, my thought with the property was to avoid a string comparison, so I don't really see that as being any different than the check against the name. If you think that's the way to go, then LGTM.

Comment (stephenplusplus) [inline packages/bigquery/src/table.js]: I think the convention of error handling is either the name or the code (short of, e.g. `err instanceof TyperError`), so let's just stick with name.

**Comment by stephenplusplus** [comment]
Ready for a final sign off, @callmehiphop!

File: packages/bigquery/src/table.js [hunk 3]
```diff
@@ -1015,18 +1015,19 @@ Table.prototype.import = function(source, metadata, callback) {
  * //-
  * function insertHandler(err, insertErrors, apiResponse) {
```
Comment (callmehiphop) [inline packages/bigquery/src/table.js]: I think you need to kill `insertErrors` here

File: packages/bigquery/src/table.js (hunk 2 above)
Comment (callmehiphop) [inline packages/bigquery/src/table.js]: Should this be `if (err && err.name === 'PartialFailureError') {`? I'm just thinking that if users copy and paste this could would throw an error if `err` is `null`.

File: packages/bigquery/src/table.js [hunk 4]
```diff
@@ -1015,18 +1015,19 @@ Table.prototype.import = function(source, metadata, callback) {
...
- *   // See https://developers.google.com/bigquery/troubleshooting-errors for
- *   // recommendations on handling errors.
+ *   //   An API error or partial failure occurred.
+ *
+ *   if (err.name === 'PartialFailureError') {
+ *     // Some rows failed to insert, while others may have succeeded.
+ *
+ *     // err.errors (object[]):
+ *     // err.errors[].row (original row object passed to `insert`)
+ *     // err.errors[].errors[].reason
```
Comment (callmehiphop) [inline packages/bigquery/src/table.js]: Is this right? `.errors[].errors[]`?

File: packages/bigquery/src/table.js [hunk 5]
```diff
@@ -1015,18 +1015,19 @@ Table.prototype.import = function(source, metadata, callback) {
...
+ *     // err.errors[].errors[].message
+ *
+ *     // See https://developers.google.com/bigquery/troubleshooting-errors for
```
Comment (callmehiphop) [inline packages/bigquery/src/table.js]: Maybe instead add this link as a `@resource`?

File: packages/bigquery/system-test/bigquery.js [hunk 6]
```diff
@@ -533,6 +528,55 @@ describe('BigQuery', function() {
         });
       });
 
+      it('should return partial errors', function(done) {
+        var data = {
+          name: 'dave',
+          breed: 'british shorthair',
```
Comment (callmehiphop) [inline packages/bigquery/system-test/bigquery.js]: But I wanna be a husky :(((

File: packages/bigtable/src/table.js [hunk 7]
```diff
@@ -769,34 +760,24 @@ Table.prototype.insert = function(entries, callback) {
...
+ *     failures. It's possible for part of your request to be completed
+ *     successfully, while the other part was not.
  *
  * @example
  * //-
  * // Insert entities. See {module:bigtable/table#insert}
  * //-
- * var callback = function(err, mutationErrors) {
+ * var callback = function(err) {
  *   if (err) {
```
Comment (callmehiphop) [inline packages/bigtable/src/table.js]: Should we document this consistently across the board? For bigquery we aren't checking if err exists, here we do the err + partial error checks in different blocks and for vision we do it in a single block.

File: packages/vision/src/index.js [hunk 8]
```diff
@@ -262,14 +261,31 @@ Vision.prototype.annotate = function(requests, callback) {
...
- * // a single feature request was not successful. Each returned detection will
- * // have an `errors` array, including any of these errors which may have
- * // occurred.
+ * // a single feature request was not successful.
  * //-
  * vision.detect('malformed-image.jpg', types, function(err, detections) {
- *   if (detections.faces.errors.length > 0) {
- *     // Errors occurred while trying to use this image for a face annotation.
+ *   if (err && err.name === 'PartialFailureError') {
+ *     err.errors = [
```
Comment (callmehiphop) [inline packages/vision/src/index.js]: Should this be commented? e.g. `// err.errors = [`

Comment (stephenplusplus) [inline packages/vision/src/index.js]: ✅

File: packages/bigquery/src/table.js (hunk 4 above)
Comment (stephenplusplus) [inline packages/bigquery/src/table.js]: Yeah :(

`err.errors` is the standard format from PartialFailureError. What goes in that array is up to the implementor; so in this case, a row can fail to insert for multiple reasons (according to [this doc](https://cloud.google.com/bigquery/docs/reference/rest/v2/tabledata/insertAll))

File: packages/bigtable/src/table.js (hunk 7 above)
Comment (stephenplusplus) [inline packages/bigtable/src/table.js]: Yes, good catch. Done.

File: packages/bigquery/system-test/bigquery.js (hunk 6 above)
Comment (stephenplusplus) [inline packages/bigquery/system-test/bigquery.js]: Well, fine then.

File: packages/bigquery/src/table.js (hunk 3 above)
Comment (stephenplusplus) [inline packages/bigquery/src/table.js]: It's a goner.

**Comment by stephenplusplus** [comment]
PTAL!

File: packages/bigquery/system-test/bigquery.js [hunk 9]
```diff
@@ -533,6 +528,55 @@ describe('BigQuery', function() {
         });
       });
 
+      it('should return partial errors', function(done) {
+        var data = {
+          name: 'dave',
+          breed: 'british husky',
```
Comment (callmehiphop) [inline packages/bigquery/system-test/bigquery.js]: A classy husky I suppose

Comment (stephenplusplus) [inline packages/bigquery/system-test/bigquery.js]: You're welcome.
