### PR TITLE
Fix pub/sub with 0 nanos

### LINKED ISSUE #1925: publishTime not visible on Pub/Sub message from emulator
I am testing out `publishTime` and it seems to not be present, at least while using the simulator. The `nanos` field is 0 which makes this check return false: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/pubsub/src/subscription.js#L367

### PR DESCRIPTION
**Pull request by arbesfeld**
Closes #1925 

Sometimes seconds/nanos are a string, so I decided to use `!= null` check instead.

### CODE REVIEW

**Comment by arbesfeld** [comment]
I signed it!

File: packages/pubsub/src/subscription.js [hunk 1]
```diff
@@ -364,7 +364,7 @@ Subscription.formatMessage_ = function(msg, encoding) {
     if (innerMessage.publishTime) {
       var publishTime = innerMessage.publishTime;
 
-      if (publishTime.seconds != null && publishTime.nanos != null) {
+      if (publishTime.seconds !== undefined && publishTime.nanos !== undefined) {
```
Comment (stephenplusplus) [inline packages/pubsub/src/subscription.js]: I think just 'is.defined(...)' will work.

Comment (arbesfeld) [inline packages/pubsub/src/subscription.js]: done!

**Comment by stephenplusplus** [comment]
Thank you!
