### PR TITLE
vision: update to v1.1

### LINKED ISSUE #2034: Vision API detectText returns TypeError: formatMethodMap[type] is not a function
#### Environment details

  - OS: MacOS
  - Node.js version: 7.6.0
  - yarn version: 0.21.3
  - @google-cloud/vision version: 0.8.0

#### Steps to reproduce

I have a testing script with sample images that worked before (i.e. successfully get the ocr text response). However, today I am having the same issue as reported in #1333 again.

Code:
```js
let vision = require('@google-cloud/vision')({
  projectId: 'my-expense-keeper',
  keyFilename: './keyfile/keyfile.json'
});

import { Observable } from '@reactivex/rxjs';

const fs = require('fs-extra');

// const types = ['labels'];
// const types = ['faces'];
// const types = ['logos'];
const types = ['text'];

const obj = fs.readJsonSync('./test-files/receipt-image-req-1.json', {throws: false});

// console.log(JSON.stringify(obj));

let buffer = new Buffer(obj.content, 'base64');

let visionObs = Observable.fromPromise(vision.detect(buffer, types));

visionObs.subscribe(
  data => {
    console.log(`Cloud vision api response: ${JSON.stringify(data)}`);
    process.exit(1);
  },
  err => {
    console.log(`Cloud vision api error: ${JSON.stringify(err)}`);
  }
);
```

Where the content is base64 encoded image content.

When run the above code with type set to 'labels', I can get the following response:
```json
[
  [
    "text",
    "label",
    "document"
  ],
  {
    "responses":[
      {
        "labelAnnotations":[
          {
            "mid":"/m/07s6nbt",
            "description":"text",
            "score":0.9377162
          },
          {
            "mid":"/m/05c0n6k",
            "description":"label",
            "score":0.591876
          },
          {
            "mid":"/m/015bv3",
            "description":"document",
            "score":0.5269188
          }
        ]
      }
    ]
  }
]
```

When run the above code with type set to 'labels', I can get the following error:
```
/Users/clarence/workspace/mek/mek-image-api/node_modules/@google-cloud/vision/src/index.js:538
          return formatMethodMap[type](annotation, options);
                                      ^
TypeError: formatMethodMap[type] is not a function
    at /Users/clarence/workspace/mek/mek-image-api/node_modules/@google-cloud/vision/src/index.js:538:39
    at Array.map (native)
    at decorateAnnotations (/Users/clarence/workspace/mek/mek-image-api/node_modules/@google-cloud/vision/src/index.js:548:16)
    at Array.map (native)
    at /Users/clarence/workspace/mek/mek-image-api/node_modules/@google-cloud/vision/src/index.js:409:10
    at /Users/clarence/workspace/mek/mek-image-api/node_modules/@google-cloud/vision/src/index.js:133:5
    at Object.handleResp (/Users/clarence/workspace/mek/mek-image-api/node_modules/@google-cloud/common/src/util.js:135:3)
    at /Users/clarence/workspace/mek/mek-image-api/node_modules/@google-cloud/common/src/util.js:466:12
    at Request.onResponse [as _callback] (/Users/clarence/workspace/mek/mek-image-api/node_modules/retry-request/index.js:120:7)
    at Request.self.callback (/Users/clarence/workspace/mek/mek-image-api/node_modules/request/request.js:186:22)
```

I have attached the image that I am using for your reference.

Thanks!
Clarence
receipt-image-1

### PR DESCRIPTION
**Pull request by stephenplusplus**

### CODE REVIEW

**Comment by callmehiphop** [comment]
@stephenplusplus looks like there's an issue with collecting coverage on CI.

**Comment by stephenplusplus** [comment]
Yeah, been working on that. Started a re-build, hopefully it goes this time.

File: packages/vision/src/index.js [hunk 1]
```diff
@@ -1404,6 +1737,22 @@ Vision.findImages_ = function(images, callback) {
 };
 
 /**
+ * Format a raw crop hint annotation response from the API.
+ *
+ * @private
+ */
+Vision.formatCropHintsAnnotation_ = function(cropHintsAnnotation, options) {
```
Comment (callmehiphop) [inline packages/vision/src/index.js]: Considering all the requests to remove verbose mode in other APIs, I'm a little hesitant about this. Maybe instead of completely altering the response we should just augment it with convenience properties.

File: packages/vision/src/index.js [hunk 2]
```diff
@@ -1566,6 +1917,49 @@ Vision.formatFaceAnnotation_ = function(faceAnnotation) {
 };
 
 /**
+ * Format a raw full text annotation response from the API.
+ *
+ * @private
+ */
+Vision.formatFullTextAnnotation_ = function(fullTextAnnotation, options) {
```
Comment (callmehiphop) [inline packages/vision/src/index.js]: re: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2041/files#r104018597

File: packages/vision/src/index.js (hunk 1 above)
Comment (stephenplusplus) [inline packages/vision/src/index.js]: The feedback is only in the Language API, since they have spent a lot of effort to make as concise of a response as possible. And since this PR is an API upgrade, as opposed to a fresh implementation, I don't want to make sweeping changes to our methods.

**Comment by stephenplusplus** [comment]
PTAL!

Regarding the simplistic doc messages, we normally use these (these are in fact copied from other methods, for example, `detectFaces()`: "Run face detection against an image". I'm sure these could be improved if we wanted to elaborate on possible use cases, etc. Currently, we only go above and beyond a long-hand form of the method name where there are technical considerations or non-obvious GCN options (i.e. not non-obvious API options). Otherwise, we link upstream and let the official doc and tech writers do the explaining. If you want to explore going deeper with our own method docs, please open a new ticket for discussion.

File: packages/vision/src/index.js [hunk 3]
```diff
@@ -575,9 +615,93 @@ Vision.prototype.detect = function(images, options, callback) {
     });
   });
 };
+
 // jscs:enable maximumLineLength
 
 /**
+ * Detect the crops within an image.
```
Comment (stephenplusplus) [inline packages/vision/src/index.js]: Given the absence of official documentation, I'm honestly not sure how to do any better. `@resource` link fixed, though 👍 (I think, hard to know for sure since the docs aren't public)

**Comment by jmuk** [comment]
Thank you for merging!

**Comment by stephenplusplus** [comment]
:+1: will be doing a bunch of releases shortly.
