### PR TITLE
spanner: add txn id to reads and remove promise support in runTransaction

### LINKED ISSUE #2118: Spanner overlapping transactions don't fail when they should?
My understanding is that if you read a cell (say the `name` column from a specific row in an `employees` table) in two different transactions, then commit a change to that cell in one of them, then a subsequent commit to that same cell from the other transaction should fail. Is this correct?

(I'm pulling this info from our docs, and making sure that these are not 'blind writes' by doing a read first -- see https://cloud.google.com/spanner/docs/transactions#rw_transaction_performance)

If so, our client library doesn't appear to do that...?

```js
var gcloud = require('google-cloud')({ projectId: 'jjg-cloud-research' });
var spanner = gcloud.spanner();
var instance = spanner.instance('test-instance');
var database = instance.database('test-database', {max: 5});
var table = database.table('employees');

var nameQuery = {keys: ['1'], columns: ['name']};

Promise.all([database.runTransaction(), database.runTransaction()]).then(
  function (txns) {
    var txn1 = txns[0][0], txn2 = txns[1][0];
    var txn = {1: txns[0][0], 2: txns[1][0]};

    function readNameFromTransaction(number) {
      return function () {
        return txn[number].read('employees', nameQuery).then(function (results) {
          console.log('txn' + number + ':', results[0][0]);
        });
      };
    }

    function changeNameFromTransaction(number) {
      return function () {
        txn[number].update('employees', {
          employee_id: '1',
          name: 'Updated by txn' + number
        });
        return txn[number].commit().then(function (results) {
          console.log('txn' + number + ':', results);
        });
      }
    }

    function readNameFromTable() {
      return table.read(nameQuery).then(function (results) {
        console.log('table:', results[0][0]);
      });
    }

    readNameFromTable()
      .then(readNameFromTransaction(1))
      .then(readNameFromTransaction(2))
      .then(changeNameFromTransaction(1))
      .then(readNameFromTable)
      .then(changeNameFromTransaction(2))
      .then(readNameFromTable)
      .catch(console.log);
  }
);
```

The output from this script looks totally successful:

```
table: [ { name: 'name', value: 'Updated by txn2' } ]
txn1: [ { name: 'name', value: 'Updated by txn2' } ]
txn2: [ { name: 'name', value: 'Updated by txn2' } ]
txn1: [ { commitTimestamp: { seconds: '1490106991', nanos: 173288000 } } ]
table: [ { name: 'name', value: 'Updated by txn1' } ]
txn2: [ { commitTimestamp: { seconds: '1490106991', nanos: 269254000 } } ]
table: [ { name: 'name', value: 'Updated by txn2' } ]
```

I expected that `txn2` commit result to be a failure because the data changed out from under us... Is my understanding wrong? or the client library wrong? or a bug in my code?

/cc @callmehiphop

### PR DESCRIPTION
**Pull request by callmehiphop**
Closes #2118 
Closes #2144

Per https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2118#issuecomment-289919717 I'm extracting out the critical parts while we decide on how best to integrate Promises within `runTransaction`.

### CODE REVIEW

File: packages/spanner/system-test/spanner.js [hunk 1]
```diff
@@ -1105,7 +1088,9 @@ var spanner = new Spanner(env);
           });
 
           if (attempts < 2) {
```
Comment (vkedia) [inline packages/spanner/system-test/spanner.js]: I dont undertstand why was this test passing so far, if transaction id was not being specified?

File: packages/spanner/system-test/spanner.js [hunk 2]
```diff
@@ -1105,7 +1088,9 @@ var spanner = new Spanner(env);
...
-            runOtherTransaction(transaction);
+            runOtherTransaction(function() {
```
Comment (vkedia) [inline packages/spanner/system-test/spanner.js]: Can you also add another test, exactly like this, except that instead of sql query you are doing read by specifying keys?

File: packages/spanner/system-test/spanner.js (hunk 1 above)
Comment (vkedia) [inline packages/spanner/system-test/spanner.js]: I wonder can it be that both these transactions end up using the same session, so the first one is actually failing due to that and not because of conflicts?
