### PR TITLE
spanner: Properly handle multi-row mutations with heterogeneous columns

### LINKED ISSUE #2411: spanner: Unable to insert multiple rows in a single table.insert/transaction.insert call when some rows lack a value for nullable columns
In [transaction-request.js](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/ca0d96cb94f7ef4e176edf221f9ee154dcf8c850/packages/spanner/src/transaction-request.js#L687-L695), there is the following (L687-695):

```javascript
mutation[method] = {
  table: table,
  columns: Object.keys(keyVals[0]),
  values: keyVals.map(function(keyVal) {
    return Object.keys(keyVal).map(function(key) {
      return codec.encode(keyVal[key]);
    });
  })
};
```

There are at least two bugs here:

1. When an array is provided to table.insert(), if some objects do not have a given key (which is perfectly valid if the column said key corresponds to is nullable), the array within `values` for this object will not be the same length as the columns array, and indices in `columns` will no longer correspond to the correct value in the `values` array for this row/object. This results in (best case) misleading error messages from Spanner about incorrect data types. Worse still, if it so happens that the value in the `values` array for this row and incorrect column index is the same type as the value for the correct column index, the insert request will succeed, and end up storing data in the wrong column entirely.

2. If a consumer of this library works around the issue above by populating missing nullable keys with `null`, as the code above relies on the order of values returned by Object.keys, the newly added values will be at the end of the array returned by Object.keys (which returns keys in insertion order), and again, the indices between the `columns` array, and the `values` array for affected rows will no longer align, with the same end result as what occurs with issue 1 above.

This could be fixed by iterating over all rows (rather than naively assuming all rows have identical keys to the first row) and collecting all unique keys into a single array which is subsequently sorted lexically, to build the value for `columns`. Likewise, the value for `values` would be constructed by mapping over `columns` (rather than `Object.keys(keyVal)`) and pulling out the corresponding value from `keyVal` to pass to `codec.encode`.

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #2411 

This adds a commit with tests on top of the work done by @jscinoz in #2417.

### CODE REVIEW

File: packages/spanner/system-test/spanner.js [hunk 1]
```diff
@@ -108,6 +108,22 @@ var spanner = new Spanner(env);
...
+          {
+            Key: generateName('id'),
+            BoolValue: true
+          },
+          {
+            Key: generateName('id'),
+            BoolValue: true,
+            IntValue: 10
+          }
+        ], done);
```
Comment (vkedia) [inline packages/spanner/system-test/spanner.js]: These semantics of automatically setting unset keys to null is very confusing in the case of updates.
If in the above code if you had `table.update` instead of `table.insert`, it would be reasonable to expect that to leave IntValue untouched in the first row but that is not what it will do.

Comment (stephenplusplus) [inline packages/spanner/system-test/spanner.js]: What's the recommendation? Do I need to change the source code (transaction-request.js) or just the test?

Comment (vkedia) [inline packages/spanner/system-test/spanner.js]: The issue is with the source code. I think we should make it mandatory for users to specify all the values explicitly. So if something is null they should explicitly specify it as null.

Comment (stephenplusplus) [inline packages/spanner/system-test/spanner.js]: Does that mean simply not accepting this change, and keeping our code the way it is currently?

Comment (vkedia) [inline packages/spanner/system-test/spanner.js]: I don't think so. The issue mentioned that even explicitly passing null can cause problem. Also we should throw an error if number of values in each array is not same.

Comment (stephenplusplus) [inline packages/spanner/system-test/spanner.js]: Thank you. The code now correct point no. 2 from #2411, but not point no. 1.

**Comment by vkedia** [comment]
What would happen if the two rows have different number of columns? I think you should error out in that case.

File: packages/spanner/src/transaction-request.js [hunk 2]
```diff
@@ -682,16 +684,28 @@ TransactionRequest.prototype.upsert = function(table, keyVals, callback) {
...
-        return codec.encode(keyVal[key]);
-      });
-    })
+  var values = keyVals.map(function(keyVal, index) {
+    var keys = Object.keys(keyVal);
+
+    var missingColumns = columns.filter(column => keys.indexOf(column) === -1);
+
+    if (missingColumns.length > 0) {
+      throw new Error([
```
Comment (stephenplusplus) [inline packages/spanner/src/transaction-request.js]: @vkedia error handling added here.
