### PR TITLE
datastore: Expose entity identification functions.

### LINKED ISSUE #2503: instanceof Datastore.Double
How to get access to entity.Double or entity.GeoPoint for instanceof ?

https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/datastore/src/index.js#L549-L551

It would be good to have Datastore.Double =  entity.Double; Datastore.GeoPoint =  entity.GeoPoint;

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - google-cloud-node version:

#### Steps to reproduce

  1. require `google-cloud`
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

### PR DESCRIPTION
**Pull request by beaulac**
Closes #2503 

Adds functionality to check if values are datastore object types (Int, Double, GeoPoint, and Key).

**4 new methods are added to datastore namespace and prototype:**
* `isInt`
* `isDouble`
* `isGeoPoint`
* `isKey`

### CODE REVIEW

File: packages/datastore/src/index.js [hunk 1]
```diff
@@ -344,6 +344,20 @@ Datastore.prototype.double = Datastore.double = function(value) {
...
+ * Helper function to check if something is a Datastore Double object.
+ *
+ * @param {*} something
+ * @return {boolean}
+ *
+ * @example
+ * datastore.isDouble(0.42); // false
+ * datastore.isDouble(datastore.double(0.42)); // true
+ */
+Datastore.prototype.isDouble = Datastore.isDouble = function(something) {
```
Comment (stephenplusplus) [inline packages/datastore/src/index.js]: Thank you for this whole PR, it is perfect! It's taken me so long to merge because I want to change the `something` var names with `value`. Otherwise, I think everything looks great 👍

Comment (beaulac) [reply packages/datastore/src/index.js]: Sure thing, I'll change the argument names from `something` to `value`.

**Comment by stephenplusplus** [comment]
Thank you!
