### PR TITLE
datastore: properly parse HTTP responses from the API

### LINKED ISSUE #910: Problems with Datastore
I am trying to get data from Datastore using the code below. However, it seems like something is not working properly.
```
var gcloud = require('gcloud')({
    projectId: myProjectId
})
var dataset = gcloud.datastore.dataset()
var employeeQuery = dataset.createQuery('Employee')
dataset.runQuery(employeeQuery, function(err, entities) {
    console.log(err)
    console.log(entities)
})
```

And here is the result.
```
{ [Error: Error during request.]
  errors: undefined,
  code: undefined,
  message: 'Error during request.',
  response: undefined }
undefined
```
I am running this on an Compute Engine instance, so there's should not be any problems with the authentication. I have tried using the Python library for Gcloud and there's no problems with it.

Also, I can use the code below to create a new entity but the 'err' in callback still give the same error, although the entity is already created.
```
var dataset = gcloud.datastore.dataset()
var key = dataset.key('Employee')
dataset.save({
  key: key,
  data: {
    name: 'Bob',
    age: 20
  }
}, function(err) {
  console.log(err)
})
```

Am I doing something wrong here ?

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #910 

The bug originally caught [here](https://github.com/GoogleCloudPlatform/gcloud-node/issues/910#issuecomment-147820786) by @electricFeel (thanks!) resulted in a re-factor, also bringing in some of the sane changes from #897 (the datastore v1beta3 upgrade).

PTAL asap, as we should get out a patch release as soon as possible.

### CODE REVIEW

File: lib/common/util.js [hunk 1]
```diff
@@ -147,50 +152,64 @@ function handleResp(err, resp, body, callback) {
...
+function parseHttpRespMessage(httpRespMessage) {
+  var parsedHttpRespMessage = {
+    resp: httpRespMessage
   };
 
-  if (resp && (resp.statusCode < 200 || resp.statusCode > 299)) {
+  if (httpRespMessage.statusCode < 200 || httpRespMessage.statusCode > 299) {
     // Unknown error. Format according to ApiError standard.
-    parsedResp.err = new util.ApiError({
+    parsedHttpRespMessage.err = util.ApiError({
```
Comment (callmehiphop) [inline lib/common/util.js]: should we `new` this up? even if it's just for the sake of clarity?

Comment (stephenplusplus) [inline lib/common/util.js]: Hmm, yes. Good catch, I didn't mean to remove it!

**Comment by callmehiphop** [comment]
Thank you, sir!
