### PR TITLE
require project ID

### LINKED ISSUE #570: Raise a helpful error if projectID is missing when making a request?
Right now, if I run the following code on an unconfigured machine, I get a scary back-end error...

```javascript
// (We're not running on App Engine or Compute Engine).
var gcloud = require('gcloud');
var dataset = gcloud.datastore.dataset();  // <-- Here is the issue (projectId === undefined)

dataset.get(datastore.key(['Person', 1], function(result) {
  console.log(result);
});
```

Seems like if we can't auto-discover the project ID or credentials, we fail with a very long error.

Could we update things so that we raise a specific exception saying "You tried to make a request with a null project ID, meaning we couldn't figure out the project ID and you also didn't tell us the project ID..."

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #570 

``` js
// Doesn't throw.
var gcloud = require('gcloud')({ keyFilename: 'key.json' });

// No project-id, will throw:
gcloud.bigquery();
gcloud.datastore.dataset();
gcloud.pubsub();
gcloud.storage();
```

Other pattern:

``` js
// Doesn't throw.
var gcloud = require('gcloud');

// No project-id, will throw:
gcloud.bigquery({ keyFilename: 'key.json' });
gcloud.datastore.dataset({ keyFilename: 'key.json' });
gcloud.pubsub({ keyFilename: 'key.json' });
gcloud.storage({ keyFilename: 'key.json' });
```

This involved fixing a lot of the examples, but the change is pretty simple.

### CODE REVIEW

**Comment by jgeewax** [comment]
What about 

```javascript
var gcloud = require('gcloud')({projectId: 'myproject'});
```

Does anything throw now?

File: test/common/util.js [hunk 1]
```diff
@@ -83,6 +87,16 @@ describe('common/util', function() {
     assert.deepEqual(REQUEST_DEFAULT_CONF, { pool: { maxSockets: Infinity } });
   });
 
+  it('should export an error for module instantiation errors', function() {
+    var missingProjectIdError = new Error([
```
Comment (jgeewax) [inline test/common/util.js]: Is this really useful? Won't it mean that we have to change the text twice if we want to modify it?

**Comment by jgeewax** [comment]
LGTM

File: test/common/util.js (hunk 1 above)
Comment (stephenplusplus) [inline test/common/util.js]: It's useful if we really love our error message, and don't want anyone to change it one day without at least having the tests catch it.

**Comment by stephenplusplus** [comment]
> What about var gcloud = require('gcloud')({projectId: 'myproject'}); Does anything throw now?

No, we only check at the instantiation of the sub-modules, which lets the user wait until the last minute to worry about giving the projectId. So as long as there's a projectId somewhere up the chain or at the time of calling, no errors will be thrown
