### PR TITLE
spanner: add object caching

### LINKED ISSUE #2356: Spanner - noStatus - TypeError: requestStream.destroy is not a function
OS: Mac OSX 10.12.4
Node.js version: 6.9.3
npm version: 5.0.0
version: 0.4.4

**After closing #2176  i run my data export in spanner. When a number of requests were in parallel the following error occurred several times.**

```
noStatus - TypeError: requestStream.destroy is not a function
    at StreamProxy.<anonymous> (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@google-cloud/spanner/src/transaction.js:375:19)
    at emitOne (events.js:96:13)
    at StreamProxy.emit (events.js:188:7)
    at ClientReadableStream.<anonymous> (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/google-gax/lib/streaming.js:130:17)
    at emitOne (events.js:96:13)
    at ClientReadableStream.emit (events.js:188:7)
    at ClientReadableStream._emitStatusIfDone (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/grpc/src/node/src/client.js:204:12)
    at ClientReadableStream._receiveStatus (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/grpc/src/node/src/client.js:180:8)
    at /Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/grpc/src/node/src/client.js:592:14
``` 

**After certain quantity of data export, the following error kept occurring constantly:**

- req.url - http://accounts.gss.local:9001/gss-api/environments/upsert
InternalServerError: err.code: 8
- err.message: Too many active sessions in database projects/spanner-gss-ge/instances/business-data/databases/system-development, limit is 30000. Increase the node count to allow more sessions.
- err.status: undefined
- err location: Environment.upsert\database.runTransaction((err, tx) => {...
- data:

```json
{
  "environmentId": "5e9d511f-e300-49d8-80ba-21c421f98b03",
  "isActive": true,
  "created": 1325376000000,
  "timestamp": 1496655116694,
  "modifierId": "system-id",
  "modifierName": "system",
  "name": "ka:ჩემი 'GSS გარემო' - paab@mail.ru|en:My 'GSS Environment' - paab@mail.ru|ru:Моя 'GSS Среда' - paab@mail.ru",
  "databaseID": "39aa56bc-f926-4df2-afe9-619c1e527afe",
  "isUnderControl": false,
  "environmentSyncURL": "",
  "linkedGSSContactID": null,
  "linkedContactID": null,
  "inputLanguages": "en ka ru",
  "usersInputLanguages": "",
  "registrationCountry": "",
  "rsgeServiceUser": "",
  "rsgeServiceUserPassword": "",
  "mainCurrencySignification": null,
  "accountingCurrencySignifications": "",
  "domain": null,
  "gssEducationIsActive": false
}
```

- apiResponse:

**I stop my process and during 20 minute from console i can not run any queries... there was same error:**
> Too many active sessions in database projects/spanner-gss-ge/instances/business-data/databases/system-development, limit is 30000. Increase the node count to allow more sessions.

**When will close sessions? look at pictures** 

screen shot 2017-06-05 at 13 55 19
screen shot 2017-06-05 at 13 55 27

I was wait around 40 minute and then delete database.
https://cloud.google.com/spanner/docs/limits
Sessions per database per node	10,000
What does it mean?
how longer do i need to wait session closing?

Thank you

### PR DESCRIPTION
**Pull request by callmehiphop**
Closes #2356

### CODE REVIEW

**Comment by callmehiphop** [comment]
@stephenplusplus I still need to write unit tests but I wanted your approval before I did that (in case you can think of a better way)

@Chipintoza is there any chance you could check this branch out and test with your application to see if you're still seeing the same issues?

**Comment by Chipintoza** [comment]
Yes today i will do this and comment you. (We have big Time Zone difference :()

**Comment by Chipintoza** [comment]
@callmehiphop i update these files and transaction.js from #2358 
The importing process has passed but during the process there was two type of errors:

1. (node:4049) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 55): TypeError: Cannot set property 'beginTime_' of undefined
**this errors was continue made after the process was stopped.**

2. noStatus - TypeError: this.stream.end is not a function
at StreamProxy._onFinish (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/google-gax/lib/streaming.js:103:17)
at StreamProxy. (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/google-gax/lib/streaming.js:76:10)
at emitNone (events.js:86:13)
at StreamProxy.emit (events.js:185:7)
at finishMaybe (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/readable-stream/lib/_stream_writable.js:504:14)
at endWritable (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/readable-stream/lib/_stream_writable.js:514:3)
at StreamProxy.Writable.end (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/readable-stream/lib/_stream_writable.js:484:41)
at StreamProxy. (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules//src/transaction.js:374:23)
at emitOne (events.js:96:13)
at StreamProxy.emit (events.js:188:7)

**and data imported in Users Table 21903 instead of 33742**

**Comment by Chipintoza** [comment]
please look  [comment](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2356#issuecomment-313310567)

**Comment by callmehiphop** [comment]
@Chipintoza sorry this kind of slipped away from me. I put in some additional error handling and rebased the code against master. Could you give this another test run? If the errors persist could you point me to the files & lines where the errors originate from? I couldn't determine that from the stacks you provided.

**Comment by Chipintoza** [comment]
@stephenplusplus i run my import and  during the process there was:

> 1. noStatus - TypeError: this.stream.end is not a function
>     at StreamProxy._onFinish (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/google-gax/lib/streaming.js:103:17)
>     at StreamProxy.<anonymous> (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/google-gax/lib/streaming.js:76:10)
>     at emitNone (events.js:86:13)
>     at StreamProxy.emit (events.js:185:7)
>     at finishMaybe (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/readable-stream/lib/_stream_writable.js:503:14)
>     at endWritable (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/readable-stream/lib/_stream_writable.js:513:3)
>     at StreamProxy.Writable.end (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/readable-stream/lib/_stream_writable.js:483:41)
>     at StreamProxy.<anonymous> (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@gss-llc/database-utils.gss.ge/node_modules/@google-cloud/spanner/src/transaction.js:375:19)
>     at emitOne (events.js:96:13)
>     at StreamProxy.emit (events.js:188:7) 

**and** 

> (node:33729) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 19): TypeError: Cannot read property 'run' of undefined
> (node:33729) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 20): TypeError: Cannot read property 'run' of undefined
> (node:33729) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 21): TypeError: Cannot read property 'run' of undefined
> (node:33729) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 22): TypeError: Cannot read property 'run' of undefined
> (node:33729) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 23): TypeError: Cannot read property 'run' of undefined
> 

**at the end - Too many active sessions,  limit is 10000**

> (node:33729) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 60): TypeError: Cannot read property 'run' of undefined
> (node:33729) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 61): TypeError: Cannot read property 'run' of undefined
> (node:33729) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 62): TypeError: Cannot read property 'run' of undefined
> (node:33729) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 63): TypeError: Cannot read property 'run' of undefined
> 
> req.url - http://accounts.gss.local:9001/gss-api/environments/upsert
> InternalServerError: err.code: 8
> err.message: Too many active sessions in database projects/spanner-gss-ge/instances/development-data/databases/system-development, limit is 10000. Increase the node count to allow more sessions.
> err.status: undefined
> err location:
> Environment.upsert\database.runTransaction((err, tx) => {...
> data:
> {"environmentId":"23e8c345-d5a4-442e-8092-e47f695662c5","isActive":true,"created":1427575695237,"timestamp":1499759051813,"modifierId":"system-id","modifierName":"system","name":"ჩემი 'GSS გარემო' - archilkuchukhidze@gmail.com|en:My 'GSS Environment' - archilkuchukhidze@gmail.com|ru:Моя 'GSS Среда' - archilkuchukhidze@gmail.com","databaseID":"39aa56bc-f926-4df2-afe9-619c1e527afe","isUnderControl":false,"environmentSyncURL":"","linkedGSSContactID":null,"linkedContactID":null,"inputLanguages":"en ka ru","usersInputLanguages":"","registrationCountry":"","rsgeServiceUser":"","rsgeServiceUserPassword":"","mainCurrencySignification":null,"accountingCurrencySignifications":"","domain":null,"gssEducationIsActive":false}
> apiResponse:
> 
>     at Function.dbUtils.getDsError (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@gss-llc/database-utils.gss.ge/index.js:213:16)
>     at error (/Users/Chipintoza/GSS Projects/accounts.gss.ge/server/tables/system/environments-table.js:327:64)
>     at database.runTransaction (/Users/Chipintoza/GSS Projects/accounts.gss.ge/server/tables/system/environments-table.js:342:27)
>     at /Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@gss-llc/database-utils.gss.ge/node_modules/@google-cloud/spanner/src/database.js:816:7
>     at /Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@gss-llc/database-utils.gss.ge/node_modules/@google-cloud/spanner/src/database.js:1040:7
>     at /Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@gss-llc/database-utils.gss.ge/node_modules/@google-cloud/spanner/src/session-pool.js:471:9
>     at /Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@gss-llc/database-utils.gss.ge/node_modules/@google-cloud/spanner/src/session-pool.js:230:9
>     at process._tickCallback (internal/process/next_tick.js:103:7)

File: packages/spanner/src/transaction.js [hunk 1]
```diff
@@ -371,7 +371,6 @@ Transaction.prototype.requestStream = function(config) {
       return;
     }
 
-    requestStream.end();
```
Comment (callmehiphop) [inline packages/spanner/src/transaction.js]: @stephenplusplus so after a lot of digging, I believe we need to remove this line. This was originally a `destroy()` call but we decided to change it to `end()` because of #2358. However it turns out this is incorrect because gRPC uses the native stream module and there is no end method for the ClientReadableStream.

I looked into why destroy doesn't work, turns out there are a couple reasons:

1. gax gives back a Duplex stream which in turn will call `end()` when it is destroyed. As mentioned before there is no end method, so we get an error.
2. gRPC uses native streams, which means that users not running 8.0.0 won't have access to a destroy method since it was recently added.

I think our only course of action is to do nothing, which upon closer inspection seems correct.

Comment (stephenplusplus) [inline packages/spanner/src/transaction.js]: SGTM

**Comment by stephenplusplus** [comment]
LGTM -- @Chipintoza do you want to give this PR a try before we merge?

**Comment by Chipintoza** [comment]
@stephenplusplus i run my imports, it take a much time, in my country no is 01:14 AM, tomorrow i will report everything.

**Comment by Chipintoza** [comment]
@stephenplusplus as i understand everything works fine!

I did not have optimal importing process and the request for update for same record was parallel many times, maybe more than 1000 time.  it looks like  hotspots occurred.

There was two types of errors

1)
```
req.url - http://accounts.gss.local:9001/gss-api/environments/upsert
DsError: err.code: 4
err.message: Deadline for Transaction exceeded.
err.status: undefined
err.stack: undefined
err location:
Environment.upsert\database.runTransaction((err, tx) => {...
data:
{"environmentId":"4ff7a78e-eff4-4ee4-a5ec-ee8d2f1ed8dc","isActive":true,"created":1413465452830,"timestamp":1500123845696,"modifierId":"system-id","modifierName":"system","name":"en:My 'GSS Environment' - irakli.kalandadze@nbg.gov.ge|ru:Моя 'GSS Среда' - irakli.kalandadze@nbg.gov.ge|ka:საქართველოს ეროვნული ბანკი","databaseID":"39aa56bc-f926-4df2-afe9-619c1e527afe","isUnderControl":false,"environmentSyncURL":"","linkedGSSContactID":null,"linkedContactID":null,"inputLanguages":"en ka ru","usersInputLanguages":"","registrationCountry":"","rsgeServiceUser":"","rsgeServiceUserPassword":"","mainCurrencySignification":null,"accountingCurrencySignifications":"","domain":null,"gssEducationIsActive":false}
apiResponse:

    at Function.dbUtils.getDsError (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@gss-llc/database-utils.gss.ge/index.js:224:28)
    at error (/Users/Chipintoza/GSS Projects/accounts.gss.ge/server/tables/system/environments-table.js:325:64)
    at Transaction.database.runTransaction [as runFn_] (/Users/Chipintoza/GSS Projects/accounts.gss.ge/server/tables/system/environments-table.js:340:27)
    at /Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@google-cloud/spanner/src/transaction.js:338:14
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

2)
```
req.url - http://accounts.gss.local:9001/gss-api/environments/upsert
DsError: err.code: undefined
err.message: Unable to create Transaction.
err.status: undefined
err.stack: Error: Unable to create Transaction.
    at /Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@google-cloud/spanner/src/database.js:892:26
    at /Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@google-cloud/spanner/src/database.js:450:13
    at /Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@google-cloud/spanner/src/session-pool.js:234:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
err location:
Environment.upsert\database.runTransaction((err, tx) => {...
data:
{"environmentId":"19c0c143-24af-4567-9b24-95d84a08d176","isActive":true,"created":1458117721470,"timestamp":1500123919337,"modifierId":"system-id","modifierName":"system","name":"ჩემი 'GSS გარემო' - d.muladze@rs.ge|en:My 'GSS Environment' - d.muladze@rs.ge|ru:Моя 'GSS Среда' - d.muladze@rs.ge","databaseID":"39aa56bc-f926-4df2-afe9-619c1e527afe","isUnderControl":false,"environmentSyncURL":"","linkedGSSContactID":null,"linkedContactID":null,"inputLanguages":"en ka ru","usersInputLanguages":"","registrationCountry":"","rsgeServiceUser":"","rsgeServiceUserPassword":"","mainCurrencySignification":null,"accountingCurrencySignifications":"","domain":null,"gssEducationIsActive":false}
apiResponse:

    at Function.dbUtils.getDsError (/Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@gss-llc/database-utils.gss.ge/index.js:224:28)
    at error (/Users/Chipintoza/GSS Projects/accounts.gss.ge/server/tables/system/environments-table.js:325:64)
    at database.runTransaction (/Users/Chipintoza/GSS Projects/accounts.gss.ge/server/tables/system/environments-table.js:340:27)
    at /Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@google-cloud/spanner/src/database.js:892:13
    at /Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@google-cloud/spanner/src/database.js:450:13
    at /Users/Chipintoza/GSS Projects/accounts.gss.ge/node_modules/@google-cloud/spanner/src/session-pool.js:234:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

As i understand all 100 sessions were in retry process and because of this Transactions could not be created.

**Am i right?**

When i optimised import, everything ran well. 

Thank you everyone

**Comment by stephenplusplus** [comment]
Thank you for testing!

@callmehiphop does everything described above sound expected?

**Comment by callmehiphop** [comment]
@stephenplusplus actually I made a small change in a recent commit, but otherwise everything sounds good. PTAL!
