### PR TITLE
fix: do not exit with 1 on empty folder

### LINKED ISSUE #4073: [typeless-sample-bot] Exit code 1 when no TypeScript files found
When the `typeless-sample-bot` doesn't find any TypeScript files, it exits with code 1. That will cause builds to fail if `check=True` when running via the synthtool `shell.run()` command.  I do think it's worth flagging as a warning, but I think that only errors in the process should lead to an exit code 1 outcome.

### PR DESCRIPTION
**Pull request by bcoe**
Fixes #4073

### CODE REVIEW

File: packages/typeless-sample-bot/test/index.ts [hunk 1]
```diff
@@ -206,12 +206,23 @@ describe('command line option', () => {
       await assert.rejects(stat(antiTarget));
     } finally {
       targets.forEach(t => {
-        rm(path.join(fixturePath, t)).catch(() => {});
+        rm(t).catch(() => {});
```
Comment (bcoe) [inline packages/typeless-sample-bot/test/index.ts:209]: There was a small bug with cleanup logic.

**Review by feywind — APPROVED** [review]
