### PR TITLE
remove topic.options.autoCreate, add topic.getMetadata

### LINKED ISSUE #696: auto-created topic and subscribe do not work together
``topic.subscribe()`` on a new topic fails. See this code:

```
var topic = pubsub.topic('my-topic');  // my-topic hasn't been created yet.
topic.subscribe('my-sub', function(err, _){ console.log(err); }
```
Will fail with a ``404: Resource not found (resource=my-topic)``,

However, this code works:

```
var topic = pubsub.topic('my-topic'); 
topic.publish({'dummy': 'message'});
topic.subscribe('my-sub', function(err, _){ console.log(err); }
```

Seems ``subscribe`` doesn't call ``createTopic`` if it doesn't exist.

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #696 
Related https://github.com/GoogleCloudPlatform/gcloud-python/issues/949

This:
- removes  `topic.options.autoCreate`
- adds `topic.getMetadata()`
- includes small refactors now possible without the overhead of supporting `autoCreate`

### CODE REVIEW

**Comment by stephenplusplus** [comment]
Assigned for a review :)

File: lib/pubsub/index.js [hunk 1]
```diff
@@ -199,16 +199,10 @@ PubSub.prototype.getTopics = function(query, callback) {
  *
  * @example
  * pubsub.createTopic('my-new-topic', function(err, topic, apiResponse) {
- *   topic.publish({
- *     data: 'New message!'
- *   }, function(err) {});
```
Comment (callmehiphop) [inline lib/pubsub/index.js]: Out of curiosity, why are we removing this example? I understand the verbiage below, but this snippet still seems relevant.

Comment (stephenplusplus) [inline lib/pubsub/index.js]: Publishing a message to a topic you created will likely have no subscriptions registered yet, which results in [the message being lost](https://github.com/GoogleCloudPlatform/gcloud-node/issues/696#issuecomment-116835719). I figured it's better to not even suggest that.

Comment (callmehiphop) [inline lib/pubsub/index.js]: Gotcha!

**Comment by callmehiphop** [comment]
Looks great, thanks!
