### PR TITLE
core: cache grpc services

### LINKED ISSUE #1164: Cache gRPC connections
Hello guys,

I use PubSub to pulish thousands of messages and a memory leak crashes my server.

Here is a Passenger screenshot using gcloud:
gcloud

Using request:
gcloud

Here is a simple repo to reproduce it: https://github.com/pierre-b/test-leak

Environnement:
- Ubuntu 14.04
- node 4.4.0
- Passenger 5.0.26
- gcloud 0.29.0

Did I miss something?
thanks for your help

### PR DESCRIPTION
**Pull request by stephenplusplus**
Fixes #1164 

@murgatroid99 when you have a chance, could you see if this is started off in the right direction? This makes a huge difference in memory usage, but I'm wondering if there are any gotchas I need to be aware of. Thanks!

### CODE REVIEW

**Comment by stephenplusplus** [comment]
@callmehiphop this is safe for review & merge.

File: lib/common/grpc-service.js [hunk 1]
```diff
@@ -217,21 +218,26 @@ GrpcService.prototype.request = function(protoOpts, reqOpts, callback) {
...
 
+  // Clean up gcloud-specific options.
+  delete reqOpts.autoPaginate;
+  delete reqOpts.autoPaginateVal;
+
+  var serviceMapKey = JSON.stringify(protoOpts);
+  var service = this.activeServiceMap_.get(serviceMapKey);
+
+  if (!service) {
+    service = new proto[protoOpts.service](
```
Comment (callmehiphop) [inline lib/common/grpc-service.js]: Should we cache this once we've created it?

Comment (stephenplusplus) [inline lib/common/grpc-service.js]: Yes :)
