### PR TITLE
compute: implement autoscaler

### LINKED ISSUE #1152: gRPC leak
Possibly relates to https://github.com/GoogleCloudPlatform/gcloud-node/issues/1140

I received this error locally running Node `v0.12.7`.

```bash
1) PubSub subscribe should create a Topic object from a string:
   Uncaught Error: .google.pubsub.v1.Subscription#a is not a field: undefined
      at Error (native)
      at MessagePrototype.set (node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:2440:58)
      at MessagePrototype.set (node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:2434:38)
      at Message (node_modules/grpc/node_modules/protobufjs/dist/ProtoBuf.js:2363:34)
      at serialize (node_modules/grpc/src/node/src/common.js:76:23)
      at Client.makeUnaryRequest [as createSubscription] (node_modules/grpc/src/node/src/client.js:303:19)
      at PubSub.GrpcService.request (lib/common/grpc-service.js:214:28)
      at lib/common/grpc-service.js:187:12
      at lib/common/grpc-service.js:285:5
      at addScope (node_modules/google-auto-auth/index.js:74:5)
      at callback (node_modules/google-auto-auth/node_modules/google-auth-library/lib/auth/googleauth.js:41:5)
      at node_modules/google-auto-auth/node_modules/google-auth-library/lib/auth/googleauth.js:124:9
```

### PR DESCRIPTION
**Pull request by stephenplusplus**
For #1073

Fixes #1152

Implements Autoscaler support.
#### To Dos
- [x] Docs
- [x] Tests
  - [x] System
    - [x] Figure out how to create an instance group before the tests run
  - [x] Unit
    - [x] autoscaler.js
    - [x] index.js
    - [x] zone.js

Creating an autoscaler...

``` js
// Easy way
var config = {
  coolDown: 30,
  cpu: 80,
  loadBalance: 40,
  maxReplicas: 5,
  minReplicas: 0,
  target: 'instance-group-name'
};

// Hard (but supported) way
var config = {
  autoscalingPolicy: {
    coolDownPeriodSec: 30,
    cpuUtilization: {
      utilizationTarget: 0.8
    },
    loadBalancingUtilization: {
      utilizationTarget: 0.4
    },
    maxNumReplicas: 5,
    minNumReplicas: 0
  },
  target: 'https://content.googleapis.com/compute/v1/projects/{PROJECT_ID}/zones/{ZONE_ID}/instanceGroupMangers/instance-group-name'
};

var zone = compute.zone('us-central1-a');
zone.createAutoscaler('autoscaler-namer', config, function(err, operation, autoscaler, apiResponse) {
  // ...
});
```

### CODE REVIEW

File: lib/compute/index.js [hunk 1]
```diff
@@ -439,6 +439,126 @@ Compute.prototype.getAddresses = function(options, callback) {
 };
 
 /**
+ * Get a list of autoscalers. For a detailed description of this method's
+ * options, see [API reference](https://cloud.google.com/compute/docs/reference/v1/autoscalers/aggregatedList).
```
Comment (callmehiphop) [inline lib/compute/index.js]: > see **the** API reference.

File: lib/compute/index.js [hunk 2]
```diff
@@ -439,6 +439,126 @@ Compute.prototype.getAddresses = function(options, callback) {
...
+ *
+ * @param {object=} options - Address search options.
+ * @param {boolean} options.autoPaginate - Have pagination handled
+ *     automatically. Default: true.
+ * @param {string} options.filter - Search filter in the format of
+ *     `{name} {comparison} {filterString}`.
+ *     - **`name`**: the name of the field to compare
+ *     - **`comparison`**: the comparison operator, `eq` (equal) or `ne`
+ *       (not equal)
+ *     - **`filterString`**: the string to filter to. For string fields, this
```
Comment (callmehiphop) [inline lib/compute/index.js]: Are the hyphens supposed to indicate something? Like a new line perhaps..? I could be wrong, but I don't believe we sniff for anything like that.

File: lib/compute/index.js [hunk 3]
```diff
@@ -439,6 +439,126 @@ Compute.prototype.getAddresses = function(options, callback) {
...
+ *       can be a regular expression.
+ * @param {number} options.maxResults - Maximum number of addresses to return.
+ * @param {string} options.pageToken - A previously-returned page token
+ *     representing part of the larger set of results to view.
+ * @param {function} callback - The callback function.
+ * @param {?error} callback.err - An error returned while making this request.
+ * @param {module:compute/autoscaler} callback.autoscalers - Autoscaler objects
```
Comment (callmehiphop) [inline lib/compute/index.js]: > {module:compute/autoscaler[]}

File: lib/compute/index.js (hunk 2 above)
Comment (stephenplusplus) [inline lib/compute/index.js]: Check it: https://googlecloudplatform.github.io/gcloud-node/#/docs/v0.28.0/compute?method=getDisks

File: lib/compute/index.js (hunk 1 above)
Comment (stephenplusplus) [inline lib/compute/index.js]: :bow:

**Comment by stephenplusplus** [comment]
Fixed those things!

**Comment by callmehiphop** [comment]
Locally I'm getting an error when testing the docs on `v0.12.7`.

```
Uncaught TypeError: The callback's first argument must be a status code
```

When running against `v5.6.0` `npm run test` seems to be timing out on something. I think this might relate to gRPC, but TBH I didn't look into it very much.

===

Other than those errors and a few documentation nitpicks, this LGTM!

File: lib/compute/index.js (hunk 2 above)
Comment (callmehiphop) [inline lib/compute/index.js]: Ah, nice!

**Comment by stephenplusplus** [comment]
My gosh, gRPC is haunting us. I'll try to get that error on 0.12.7.

**Comment by stephenplusplus** [comment]
If you strictly run `node_modules/mocha/bin/mocha test/docs.js`, you get the `Uncaught TypeError`?

**Comment by callmehiphop** [comment]
> If you strictly run node_modules/mocha/bin/mocha test/docs.js, you get the Uncaught TypeError?

Nope!

**Comment by callmehiphop** [comment]
Although it is still hanging on something

**Comment by stephenplusplus** [comment]
Please check all that apply:

v0.12.7
- [ ] `npm test` hangs
- [ ] `node_modules/mocha/bin/mocha test/docs.js` hangs
- [ ] `npm test` returns `Uncaught TypeError: The callback's first argument must be a status code`
- [ ] `node_modules/mocha/bin/mocha test/docs.js` returns `Uncaught TypeError: The callback's first argument must be a status code`

v5.6.0
- [ ] `npm test` hangs
- [ ] `node_modules/mocha/bin/mocha test/docs.js` hangs
- [ ] `npm test` returns `Uncaught TypeError: The callback's first argument must be a status code`
- [ ] `node_modules/mocha/bin/mocha test/docs.js` returns `Uncaught TypeError: The callback's first argument must be a status code`

As you probably guessed, none of the above happens for me locally. There's obviously something going on, but I don't really know where to start to find it.

**Comment by stephenplusplus** [comment]
Just for reference, found the origin of the status code error: https://github.com/grpc/grpc/blob/72724bce84b4bc027ce8dd3f7508b9216788434b/src/node/ext/call_credentials.cc#L176

**Comment by stephenplusplus** [comment]
If you run the same tests prior to this commit, will you get the same errors?

**Comment by stephenplusplus** [comment]
I pushed a commit to see if anything improves. Travis is never happy, so I'm not expecting it to win him over. But maybe it'll help what you're getting locally. If it does, I'll send a different PR with that change.

**Comment by callmehiphop** [comment]
> If you run the same tests prior to this commit, will you get the same errors?

I don't, I'm somehow magically all green when I run against master.

**Comment by stephenplusplus** [comment]
It makes no sense, man!!

**Comment by callmehiphop** [comment]
I just pulled your latest commit! It helped, lol.

**Comment by stephenplusplus** [comment]
That's awesome. The only thing I can't line up is why this PR revealed the problem. Oh well, as long as it works for us all, that's all that matters. I'll just add a test for it and we can merge it in with this PR. We talked about it most here anyway, so finding it later, this PR would help.

I'm thinking it solves #1140 and #1152 - wdyt?

**Comment by callmehiphop** [comment]
SGTM.. I'm a little lost on what's going on, but maybe we should open a new issue for investigating gRPC stuff since it has been giving us weird/random errors.

**Comment by stephenplusplus** [comment]
Yeah, we can leave #1140 open as a place to log issues that might relate to gRPC.

I think this is ready for a merge!
