### PR TITLE
build: fix readme generation, do not fail if product documentation does not exist

### LINKED ISSUE #3387: libraries.json missing repo metadata update
The `libraries.json` file is missing metadata for `@google-cloud/iam`, so it may not be updating to reflect all client library additions/updates.

### PR DESCRIPTION
**Pull request by sofisl**
Fixes #3387

### CODE REVIEW

File: bin/generate-readme.mjs [hunk 1]
```diff
@@ -152,13 +152,23 @@ async function processMetadata (repoMetadata) {
...
-        validateStatus: () => true
-      });
-      const remoteUrlExists = res.status !== 404;
+      try {
+        res = await request({
+          url: supportDocsUrl,
+          method: 'HEAD',
+          validateStatus: () => true
+        });
+      } catch (err) {
```
Comment (bcoe) [inline bin/generate-readme.mjs:168]: I would look at the error `code` and only set `remoteUrlExists = false` if the error returned is a 404 (indicating that it doesn't exist).

This way we don't mess up the README.md if there happen to be spurious 500s.

**Review by bcoe — CHANGES_REQUESTED** [review]

File: bin/generate-readme.mjs [hunk 2]
```diff
@@ -152,13 +152,25 @@ async function processMetadata (repoMetadata) {
         supportDocsUrl = 'https://cloud.google.com/stackdriver/docs/getting-support';
       }
 
+      if (!supportDocsUrl.match(/https/)) {
```
Comment (alexander-fenster) [inline bin/generate-readme.mjs:155]: Let's do `/^https:/` to avoid possible matches in the middle of the string.

**Review by alexander-fenster — APPROVED** [review]
